# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sorina/Desktop/Laboratory/cern_winter_school/2018/detector/detector.srcs/sources_1/bd/detector_bd/ip/detector_bd_auto_pc_0/detector_bd_auto_pc_0.xci
# IP: The module: 'detector_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/2018/detector/detector.srcs/sources_1/bd/detector_bd/ip/detector_bd_auto_pc_0/detector_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'detector_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/sorina/Desktop/Laboratory/cern_winter_school/2018/detector/detector.srcs/sources_1/bd/detector_bd/ip/detector_bd_auto_pc_0/detector_bd_auto_pc_0.xci
# IP: The module: 'detector_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/2018/detector/detector.srcs/sources_1/bd/detector_bd/ip/detector_bd_auto_pc_0/detector_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'detector_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
