set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/CERN_projects/Peripherals/Peripherals.srcs/sources_1/bd/Peripherals/ip/Peripherals_processing_system7_0_0/Peripherals_processing_system7_0_0.xdc rfile:../../../Peripherals.srcs/sources_1/bd/Peripherals/ip/Peripherals_processing_system7_0_0/Peripherals_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:Peripherals_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/CERN_projects/Peripherals/Peripherals.srcs/constrs_1/new/constraints.xdc rfile:../../../Peripherals.srcs/constrs_1/new/constraints.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports PWM_RED]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports PWM_BLUE]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports PWM_GREEN]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports PWM_BUZZER]
