webtalk_init -webtalk_dir /home/sorina/Desktop/Laboratory/cern_winter_school/2018/Peripherals/Peripherals.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-11-19 19:01:59" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bseod3nqmm98nvanrc4itug0tb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "11.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1511114419000" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.3" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1511114419000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1511114519353"
webtalk_transmit -clientid 1479637597 -regid "" -xml /home/sorina/Desktop/Laboratory/cern_winter_school/2018/Peripherals/Peripherals.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sorina/Desktop/Laboratory/cern_winter_school/2018/Peripherals/Peripherals.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sorina/Desktop/Laboratory/cern_winter_school/2018/Peripherals/Peripherals.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
