# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nets.xdc

# Block Designs: bd/Peripherals/Peripherals.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals || ORIG_REF_NAME==Peripherals}]

# IP: bd/Peripherals/ip/Peripherals_PWM_0_1/Peripherals_PWM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals_PWM_0_1 || ORIG_REF_NAME==Peripherals_PWM_0_1}]

# IP: bd/Peripherals/ip/Peripherals_processing_system7_0_2/Peripherals_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals_processing_system7_0_2 || ORIG_REF_NAME==Peripherals_processing_system7_0_2}]

# IP: bd/Peripherals/ip/Peripherals_ps7_0_axi_periph_1/Peripherals_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals_ps7_0_axi_periph_1 || ORIG_REF_NAME==Peripherals_ps7_0_axi_periph_1}]

# IP: bd/Peripherals/ip/Peripherals_rst_ps7_0_50M_0/Peripherals_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals_rst_ps7_0_50M_0 || ORIG_REF_NAME==Peripherals_rst_ps7_0_50M_0}]

# IP: bd/Peripherals/ip/Peripherals_auto_pc_0/Peripherals_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Peripherals_auto_pc_0 || ORIG_REF_NAME==Peripherals_auto_pc_0}]

# XDC: bd/Peripherals/ip/Peripherals_processing_system7_0_2/Peripherals_processing_system7_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Peripherals_processing_system7_0_2 || ORIG_REF_NAME==Peripherals_processing_system7_0_2}] {/inst }]/inst ]]

# XDC: bd/Peripherals/ip/Peripherals_rst_ps7_0_50M_0/Peripherals_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Peripherals_rst_ps7_0_50M_0 || ORIG_REF_NAME==Peripherals_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/Peripherals/ip/Peripherals_rst_ps7_0_50M_0/Peripherals_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Peripherals_rst_ps7_0_50M_0 || ORIG_REF_NAME==Peripherals_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/Peripherals/ip/Peripherals_rst_ps7_0_50M_0/Peripherals_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/Peripherals/ip/Peripherals_auto_pc_0/Peripherals_auto_pc_0_ooc.xdc

# XDC: bd/Peripherals/Peripherals_ooc.xdc
