# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xci
# IP: The module: 'bd_pwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_pwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xci
# IP: The module: 'bd_pwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_pwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
