# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xci
# IP: The module: 'BuzzerLED_block_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BuzzerLED_block_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xci
# IP: The module: 'BuzzerLED_block_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BuzzerLED_block_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
