# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.cache/wt [current_project]
set_property parent.project_path /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part myir.com:mys-7z010:part0:2.1 [current_project]
set_property ip_repo_paths /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/ip_repo [current_project]
set_property ip_output_repo /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/hdl/BuzzerLED_block_design_wrapper.vhd
add_files /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/BuzzerLED_block_design.bd
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_rst_ps7_0_50M_0/BuzzerLED_block_design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_rst_ps7_0_50M_0/BuzzerLED_block_design_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_rst_ps7_0_50M_0/BuzzerLED_block_design_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_auto_pc_0/BuzzerLED_block_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/BuzzerLED_block_design_ooc.xdc]
set_property is_locked true [get_files /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/vivado_project/BuzzerLED/BuzzerLED.srcs/sources_1/bd/BuzzerLED_block_design/BuzzerLED_block_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/constraints/system.xdc
set_property used_in_implementation false [get_files /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/constraints/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top BuzzerLED_block_design_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef BuzzerLED_block_design_wrapper.dcp

catch { report_utilization -file BuzzerLED_block_design_wrapper_utilization_synth.rpt -pb BuzzerLED_block_design_wrapper_utilization_synth.pb }
