# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/hdl/synthesis/constraints/system.xdc

# Block Designs: bd/BuzzerLED_block_design/BuzzerLED_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design || ORIG_REF_NAME==BuzzerLED_block_design}]

# IP: bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_processing_system7_0_0/BuzzerLED_block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design_processing_system7_0_0 || ORIG_REF_NAME==BuzzerLED_block_design_processing_system7_0_0}]

# IP: bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_PWM_0_0/BuzzerLED_block_design_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design_PWM_0_0 || ORIG_REF_NAME==BuzzerLED_block_design_PWM_0_0}]

# IP: bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_ps7_0_axi_periph_0/BuzzerLED_block_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==BuzzerLED_block_design_ps7_0_axi_periph_0}]

# IP: bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_rst_ps7_0_50M_0/BuzzerLED_block_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==BuzzerLED_block_design_rst_ps7_0_50M_0}]

# IP: bd/BuzzerLED_block_design/ip/BuzzerLED_block_design_auto_pc_0/BuzzerLED_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BuzzerLED_block_design_auto_pc_0 || ORIG_REF_NAME==BuzzerLED_block_design_auto_pc_0}]

# XDC: bd/BuzzerLED_block_design/BuzzerLED_block_design_ooc.xdc
