# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PSDesign/PSDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PSDesign || ORIG_REF_NAME==PSDesign}]

# IP: bd/PSDesign/ip/PSDesign_processing_system7_0_0/PSDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PSDesign_processing_system7_0_0 || ORIG_REF_NAME==PSDesign_processing_system7_0_0}]

# XDC: bd/PSDesign/ip/PSDesign_processing_system7_0_0/PSDesign_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PSDesign_processing_system7_0_0 || ORIG_REF_NAME==PSDesign_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/PSDesign/PSDesign_ooc.xdc
