# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.cache/wt [current_project]
set_property parent.project_path /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.srcs/sources_1/bd/PSDesign/hdl/PSDesign_wrapper.vhd
add_files /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.srcs/sources_1/bd/PSDesign/PSDesign.bd
set_property used_in_implementation false [get_files -all /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.srcs/sources_1/bd/PSDesign/ip/PSDesign_processing_system7_0_0/PSDesign_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.srcs/sources_1/bd/PSDesign/PSDesign_ooc.xdc]
set_property is_locked true [get_files /media/sf_sorinalupu/VIvado_XILINX/Vivado/2016.3/ZTurnPs/ZTurnPs.srcs/sources_1/bd/PSDesign/PSDesign.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top PSDesign_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef PSDesign_wrapper.dcp

catch { report_utilization -file PSDesign_wrapper_utilization_synth.rpt -pb PSDesign_wrapper_utilization_synth.pb }
