# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sorina/Desktop/Laboratory/cern_winter_school/2018/constraints/nets.xdc

# Block Designs: bd/detector_bd/detector_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd || ORIG_REF_NAME==detector_bd}]

# IP: bd/detector_bd/ip/detector_bd_pwm_verilog_0_0_1/detector_bd_pwm_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd_pwm_verilog_0_0 || ORIG_REF_NAME==detector_bd_pwm_verilog_0_0}]

# IP: bd/detector_bd/ip/detector_bd_processing_system7_0_0_1/detector_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd_processing_system7_0_0 || ORIG_REF_NAME==detector_bd_processing_system7_0_0}]

# IP: bd/detector_bd/ip/detector_bd_ps7_0_axi_periph_0/detector_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==detector_bd_ps7_0_axi_periph_0}]

# IP: bd/detector_bd/ip/detector_bd_rst_ps7_0_50M_0/detector_bd_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==detector_bd_rst_ps7_0_50M_0}]

# IP: bd/detector_bd/ip/detector_bd_auto_pc_0/detector_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detector_bd_auto_pc_0 || ORIG_REF_NAME==detector_bd_auto_pc_0}]

# XDC: bd/detector_bd/detector_bd_ooc.xdc
