# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sorina/Desktop/Laboratory/hdl/synthesis/constraints/system.xdc

# Block Designs: bd/LED_BUZZER_BD/LED_BUZZER_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD || ORIG_REF_NAME==LED_BUZZER_BD}]

# IP: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_processing_system7_0_0/LED_BUZZER_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_processing_system7_0_0 || ORIG_REF_NAME==LED_BUZZER_BD_processing_system7_0_0}]

# IP: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_PWM_0_0/LED_BUZZER_BD_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_PWM_0_0 || ORIG_REF_NAME==LED_BUZZER_BD_PWM_0_0}]

# IP: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_ps7_0_axi_periph_0/LED_BUZZER_BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==LED_BUZZER_BD_ps7_0_axi_periph_0}]

# IP: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_rst_ps7_0_50M_0/LED_BUZZER_BD_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0}]

# IP: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_auto_pc_0/LED_BUZZER_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_auto_pc_0 || ORIG_REF_NAME==LED_BUZZER_BD_auto_pc_0}]

# XDC: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_processing_system7_0_0/LED_BUZZER_BD_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_processing_system7_0_0 || ORIG_REF_NAME==LED_BUZZER_BD_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_rst_ps7_0_50M_0/LED_BUZZER_BD_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_rst_ps7_0_50M_0/LED_BUZZER_BD_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==LED_BUZZER_BD_rst_ps7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_rst_ps7_0_50M_0/LED_BUZZER_BD_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/LED_BUZZER_BD/ip/LED_BUZZER_BD_auto_pc_0/LED_BUZZER_BD_auto_pc_0_ooc.xdc

# XDC: bd/LED_BUZZER_BD/LED_BUZZER_BD_ooc.xdc
