# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.cache/wt [current_project]
set_property parent.project_path /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part myir.com:mys-7z010:part0:2.1 [current_project]
set_property ip_repo_paths /home/isotdaq/lab14/demo/hdl/modules/PWM_1.0 [current_project]
set_property ip_output_repo /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/imports/hdl/bd_pwm_wrapper.vhd
add_files /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/bd_pwm.bd
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_rst_ps7_0_50M_0/bd_pwm_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_rst_ps7_0_50M_0/bd_pwm_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_rst_ps7_0_50M_0/bd_pwm_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/ip/bd_pwm_auto_pc_0/bd_pwm_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/bd_pwm_ooc.xdc]
set_property is_locked true [get_files /home/isotdaq/lab14/demo/hdl/synthesis/vivado_project/LEDBuzzer.srcs/sources_1/bd/bd_pwm/bd_pwm.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/isotdaq/lab14/demo/hdl/synthesis/constraints/system.xdc
set_property used_in_implementation false [get_files /home/isotdaq/lab14/demo/hdl/synthesis/constraints/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top bd_pwm_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef bd_pwm_wrapper.dcp

catch { report_utilization -file bd_pwm_wrapper_utilization_synth.rpt -pb bd_pwm_wrapper_utilization_synth.pb }
