# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/isotdaq/lab14/demo/hdl/synthesis/constraints/system.xdc

# Block Designs: bd/bd_pwm/bd_pwm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm || ORIG_REF_NAME==bd_pwm}]

# IP: bd/bd_pwm/ip/bd_pwm_PWM_0_0/bd_pwm_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm_PWM_0_0 || ORIG_REF_NAME==bd_pwm_PWM_0_0}]

# IP: bd/bd_pwm/ip/bd_pwm_processing_system7_0_0/bd_pwm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm_processing_system7_0_0 || ORIG_REF_NAME==bd_pwm_processing_system7_0_0}]

# IP: bd/bd_pwm/ip/bd_pwm_ps7_0_axi_periph_0/bd_pwm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_pwm_ps7_0_axi_periph_0}]

# IP: bd/bd_pwm/ip/bd_pwm_rst_ps7_0_50M_0/bd_pwm_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm_rst_ps7_0_50M_0 || ORIG_REF_NAME==bd_pwm_rst_ps7_0_50M_0}]

# IP: bd/bd_pwm/ip/bd_pwm_auto_pc_0/bd_pwm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_pwm_auto_pc_0 || ORIG_REF_NAME==bd_pwm_auto_pc_0}]

# XDC: bd/bd_pwm/bd_pwm_ooc.xdc
